version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      CONFIG_PATH: "/config/dev.yaml"
    depends_on:
      - redis
    networks:
      - yoopass-net

  redis:
    image: "redis:alpine"
    networks:
      - yoopass-net

networks:
  yoopass-net:
    driver: bridge
